### ISSUE TITLE
Odometer not updating

### ISSUE THREAD

**Issue by TheRealLink** [DasBasti/SmartHashtag#237]
## Version of the custom_component

0.6.3

## Configuration

```yaml
Add your logs here.
```

## Describe the bug

The odometer is only updated one after a restart of home assistant:

![Image](https://github.com/user-attachments/assets/11c1d1ea-c100-418d-80a6-a055656fb177)

## Debug log

```text

Add your logs here.

```

**Comment by cmdrfletcher** [comment]
Also the Smart 12V Batterie Ladestand.

**Comment by DasBasti** [comment]
thanks for the info. Any chance to get a log file from you? I have a suspicion that the integration gets some unexpected data and hangs after that. But I was not able to reproduce it myself.

**Comment by cmdrfletcher** [comment]
I have noticed that the values are updated when I reload the integration. Where can I access the logs you want?

**Comment by cmdrfletcher** [comment]
`2025-03-06 11:34:19.003 ERROR (MainThread) [homeassistant.helpers.event] Error while dispatching event for sensor.smart_kilometerstand to <Job track state_changed event {'sensor.smart_kilometerstand'} HassJobType.Callback <bound method TrackTemplateResultInfo._refresh of <TrackTemplateResultInfo {Template<template=({{ states('sensor.smart_kilometerstand')}}) renders=6>: <RenderInfo Template<template=({{ states('sensor.smart_kilometerstand')}}) renders=6> all_states=False all_states_lifecycle=False domains=frozenset() domains_lifecycle=frozenset() entities=frozenset({'sensor.smart_kilometerstand'}) rate_limit=None has_time=False exception=None is_static=False>}>>>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 640, in state
    numerical_value = float(value)  # type:ignore[arg-type]
ValueError: could not convert string to float: 'unavailable'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 355, in _async_dispatch_entity_id_event
    hass.async_run_hass_job(job, event)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 940, in async_run_hass_job
    hassjob.target(*args)
    ~~~~~~~~~~~~~~^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1312, in _refresh
    self.hass.async_run_hass_job(self._job, event, updates)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 940, in async_run_hass_job
    hassjob.target(*args)
    ~~~~~~~~~~~~~~^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/template/template_entity.py", line 463, in _handle_results
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1023, in async_write_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1148, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1085, in __async_calculate_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1029, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 642, in state
    raise ValueError(
    ...<5 lines>...
    ) from err
ValueError: Sensor sensor.smart_kilometerstand_total_increasing has device class 'distance', state class 'total_increasing' unit 'km' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'unavailable' (<class 'str'>)
2025-03-06 11:34:21.544 DEBUG (MainThread) [custom_components.smarthashtag] Finished fetching smarthashtag data in 2.561 seconds (success: True)
2025-03-06 11:34:21.547 INFO (MainThread) [custom_components.smarthashtag] Updatefrequency set for charging: 0:05:00
2025-03-06 11:34:21.553 INFO (MainThread) [custom_components.smarthashtag] Updatefrequency set for driving: 0:05:00
2025-03-06 11:34:21.621 INFO (MainThread) [custom_components.smarthashtag] Updatefrequency set for climate: 0:05:00
2025-03-06 11:34:21.622 DEBUG (MainThread) [custom_components.smarthashtag] No heating level found for HeatingLocation.DRIVER_SEAT
2025-03-06 11:34:21.622 DEBUG (MainThread) [custom_components.smarthashtag] No heating level found for HeatingLocation.PASSENGER_SEAT
2025-03-06 11:34:21.622 DEBUG (MainThread) [custom_components.smarthashtag] No heating level found for HeatingLocation.STEERING_WHEEL
2025-03-06 11:34:21.622 DEBUG (MainThread) [custom_components.smarthashtag] No heating level found for HeatingLocation.DRIVER_SEAT
2025-03-06 11:34:21.622 DEBUG (MainThread) [custom_components.smarthashtag] No heating level found for HeatingLocation.PASSENGER_SEAT
2025-03-06 11:34:21.622 DEBUG (MainThread) [custom_components.smarthashtag] No heating level found for HeatingLocation.STEERING_WHEEL
2025-03-06 11:34:22.193 DEBUG (MainThread) [custom_components.smarthashtag] Finished fetching smarthashtag data in 0.597 seconds (success: True)`

**Comment by DasBasti** [comment]
Thanks. It seams to be an issue with the web data having an unexpected value, I will have a look into it.

**Comment by defux-23** [comment]
I was just about to open an issue for this, as I have exactly the same behaviour for the Odometer - if it helps, I can also give you logs (though I don't know where to find, there was nothing appearing in the "Einstellungen - System - Protokolle" logs that was related to the smart integration.

**Comment by DasBasti** [comment]
@defux-23, @cmdrfletcher please check out 0.6.4 pre release to see if your issue is fixed

**Comment by cmdrfletcher** [comment]
@DasBasti How can I install this version?

**Comment by cmdrfletcher** [comment]
Okay, I've installed it, but it still shows v0.6.3. Unfortunately, **Smart Kilometerstand** is still not updated. I still have to reload the integration.

**Comment by DasBasti** [comment]
Ok, thank you for testing. I will look further into the issue

**Comment by guggu1** [comment]
here, many other entities are set to 'unavailable'

![Image](https://github.com/user-attachments/assets/c28a6ef7-eb07-40e7-ac48-ba1f1900df46)

**Comment by DasBasti** [comment]
if you try version 0.6.6 and activate debug logs we might get to why that is. I suspect that you get a different response from the web service than me. I would like to use your response in the test data for the library. So if you could share some log lines starting with `ValueError ... - Data: ...` that would be helpful

![Image](https://github.com/user-attachments/assets/140b4fd7-4552-47e2-9405-a4b09d8c528c)

**Comment by DasBasti** [comment]
I had a little play around with changing the web data and did not manage to reproduce your situation. Do you have any custom modifications with the sensor data? The log file indicates that some templating is not working and as far as I know this integration does not directly make use of templates

**Comment by DasBasti** [comment]
strange, it shows that it only once successfully got data. Could you please increase the log level by adding this to you configuration.yaml
```
logger:
  default: error
  logs:
    custom_components.smarthashtag: debug
    pysmarthashtag: debug
```
The let it run for a few minutes (15 or so) and than remove all mentions of your VIN before uploading

**Comment by cmdrfletcher** [comment]
Here is a new debug log:

```
2025-03-11 17:09:33.780 ERROR (MainThread) [homeassistant.helpers.event] Error while dispatching event for sensor.smart_kilometerstand_2 to <Job track state_changed event {'sensor.smart_kilometerstand_2'} HassJobType.Callback <bound method TrackTemplateResultInfo._refresh of <TrackTemplateResultInfo {Template<template=({{ states('sensor.smart_kilometerstand_2')}}) renders=14>: <RenderInfo Template<template=({{ states('sensor.smart_kilometerstand_2')}}) renders=14> all_states=False all_states_lifecycle=False domains=frozenset() domains_lifecycle=frozenset() entities=frozenset({'sensor.smart_kilometerstand_2'}) rate_limit=None has_time=False exception=None is_static=False>}>>>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 640, in state
    numerical_value = float(value)  # type:ignore[arg-type]
ValueError: could not convert string to float: 'unavailable'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 355, in _async_dispatch_entity_id_event
    hass.async_run_hass_job(job, event)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 940, in async_run_hass_job
    hassjob.target(*args)
    ~~~~~~~~~~~~~~^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1312, in _refresh
    self.hass.async_run_hass_job(self._job, event, updates)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 940, in async_run_hass_job
    hassjob.target(*args)
    ~~~~~~~~~~~~~~^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/template/template_entity.py", line 463, in _handle_results
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1023, in async_write_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1148, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1085, in __async_calculate_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1029, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 642, in state
    raise ValueError(
    ...<5 lines>...
    ) from err
```

**Comment by Kanecaine** [comment]
Having the same issue that some (maybe all?) entities are currently only updated by reloading the integration. Also using the app on the smartphone seems to trigger an update. I can reproduce this for the soc and central locking status. Only the „last update“-entity shows a new state.

**Comment by DasBasti** [comment]
@TheRealLink I looked through the logs and nothing springs into my eye. I will look a little further into it.

**Comment by DasBasti** [comment]
I cannot find the error that @cmdrfletcher is having in the attached logs so I would suspect those are two different issues. I also saw that in the first log the issue was with sensor.smart_kilometerstand and in the second sensor.smart_kilometerstand_2 so two different named sensors. I know that there was an issue a couple of versions ago that caused addition of sensor entities. 

If you could, please remove the integration, uninstall the extension, restart, install and restart again.

**Comment by guggu1** [comment]
I have a Standby HASS which run the Smart# integration version v.0.6.2. This does not have the stated problem of the odometer reading not being available. I have upgraded to V0.6.8 on that Standby server -> I get the problem. I then reinstalled a complete backup of the standby server made before I upgraded Smart# -> Odometer OK.

I have tried to install an older version on my main server, but cannot figure out how that can be achieved. The files do not seem to be available in the repository.

**Comment by guggu1** [comment]
my workaround: copied to files in customcomponents/smarthashtag from my Standby server running integration v0.6.2 to the Main server. Restarted HASS Main -> Odometer reading available. 

Hence it MUST be a bug in the newer version(s) of the integration, not some data problem.

**Comment by DasBasti** [comment]
I just saw that I have the same issue with this sensor. So I can now have a closer look into it.

**Comment by davdl92** [comment]
> In the Hello Smart and the 3rd party Smart# (btw: much better that the official one!) the data are alway available. I guess the third party people are using the same api as this integration

I'm having the same issue; can you point me to the "3rd party Smart#" you mentioned? Is it something available on Play store (Android) or apk only?

**Comment by cmdrfletcher** [comment]
@davdl92 https://play.google.com/store/apps/details?id=org.more.hashtag

**Comment by DasBasti** [comment]
I have pushed a new version 0.6.8 that should have the odometer and other sensors working again. Please let me know if it works for you, I saw it working today in my development setup

**Comment by cmdrfletcher** [comment]
Hello Basti, I have downloaded and installed 0.68 again. But I still have to reload the integration to update the Odometer.

**Comment by guggu1** [comment]
Same or even more severe problem here: re-dowloded the integration from HACS, restarted HASS -> in Lovelace I get "This entity is currently unavailable: ...". Restart HASS one more time -> same problem. Reloaded integration -> odometer still not available.

Home Assistant Core 2025.2.3
Home Assistant Operating System: 14.2

On my production server the integration runs quite reliably. Odometer reading much more often available 
Smart# Integration: 0.6.2
Home Assistant Core 2025.2.3
Home Assistant Operating System: 14.2

Same car.

Mystery?!

Probably not:

**I found out that I have 2 odometer entities (as for many others). Maybe a left over from earlier integration versions/renaming on the server side:**. The one that works has the sufficx "...._2"


CCS

**Comment by guggu1** [comment]
0.6.2 is not available in HACS. 0.6.3 is. I donwgraded to 0.6.2 by copying the files from an old backup. Any other procedure?

**Comment by DasBasti** [comment]
v 0.6.2 is available here: https://github.com/DasBasti/SmartHashtag/releases/tag/v0.6.2
I am onto getting it working again :)

**Comment by DasBasti** [comment]
I tested it in 0.7.0 today and it works for my car on my homeassistant. Please reopen if issue still persists for you.
